title: Michele Orrù
email: michele.orru@ens.fr
description: > # this means to ignore newlines until "baseurl:"
  Michele Orrù, Cryptographer
baseurl: "" # the subpath of your site, e.g. /blog
url: "tumbolandia.net" # the base hostname & protocol for your site
domain: "tumbolandia.net"
twitter_username: mmaker
github_username:  mmaker
gpgkey: "0x4D817DFFDF5E18F1"

# Build settings
markdown: kramdown
excerpt_separator: ""
highlighter: rouge
kramdown:
  math_engine:
  parse_block_html: true
