# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Michele Orrù
email: michele.orru@ens.fr
description: > # this means to ignore newlines until "baseurl:"
  Michele Orrù PhD ENS
baseurl: "/~orru" # the subpath of your site, e.g. /blog
url: "http://www.di.ens.fr" # the base hostname & protocol for your site
twitter_username: mmaker
github_username:  mmaker
gpgkey: "0x4D817DFFDF5E18F1"

# Build settings
markdown: kramdown
excerpt_separator: ""
highlighter: rouge
kramdown:
  math_engine: 
  parse_block_html: true
